version: 1.0.{build}
build_cloud: libcc-20
skip_branch_with_pr: true
image: libcc-20core
environment:
  DISABLE_CRASH_REPORTER_TESTS: true
  MOCHA_FILE: test-results.xml
  MOCHA_REPORTER: mocha-junit-reporter
  matrix:
  - TARGET_ARCH: ia32
  - TARGET_ARCH: x64
build_script:
- ps: >-
    Add-Path "$env:ProgramFiles (x86)\Windows Kits\10\Debuggers\x64"

    $env:path = "$env:ProgramFiles (x86)\Windows Kits\10\Debuggers\x64;$env:path"

    $Message = (git log --format=%B -n 1 HEAD) | Out-String

    if (($Message.StartsWith('Bump')) -Or (Test-Path Env:\RUN_RELEASE_BUILD)) {
      $env:ELECTRON_RELEASE = '1'
      if (Test-Path Env:\RUN_RELEASE_BUILD) {
        Write-Output "release build triggered from api"
      }
      python script\bootstrap.py --target_arch=$env:TARGET_ARCH
      python script\build.py -c R
      python script\create-dist.py
    } else {
      python script\bootstrap.py --target_arch=$env:TARGET_ARCH --dev
      python script\build.py -c D
    }

    if ($? -ne 'True') {
      throw "Build failed with exit code $?"
    } else {
      "Build succeeded."
    }
test_script:
- ps: >-
    python script\test.py --ci --rebuild_native_modules
    if ($? -ne 'True') {
      throw "Tests failed with exit code $?"
    } else {
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://windows-ci.electronjs.org/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results.xml))
      "Tests succeeded."
    }
    python script\verify-ffmpeg.py
    if ($? -ne 'True') {
      throw "Verify ffmpeg failed with exit code $?"
    } else {
      "Verify ffmpeg succeeded."
    }
artifacts:
- path: test-results.xml
  name: test-results.xml
